config/routes.rb
MassMailer::Application.routes.draw do
  get "redirect/direct"

mount WillFilter::Engine => "/will_filter"
  mount Mercury::Engine => '/'

  resources :server_lists do
    collection do 
      post :remove_many
      post :add_servers
    end
  end

  resources :redirect, :only => :direct

  resources :list_mails do
    member do
      get :deliver
    end
  end

  resources :servers

  resources :mailing_lists do
    collection do 
      post :import
      post :remove_many
      post :add_emails
      get :add
    end
  end

  resources :email_submissions do
    member do
      get :deliver
    end
  end

  get "home_page/SendMail"

  get "scaffold/SendMail"

  resources :email_messages do
    member { post :update_html }
    member { get :view }
  end

  devise_for :users

  resources :emails 

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  match "/delayed_job" => DelayedJobWeb, :anchor => false
  match '/messagehtml' => 'email_messages#editor'
  match '/mailing_lists/:id/add' => 'mailing_lists#add'
  match '/view' => 'email_messages#view'
  root :to => 'list_mails#index'
end

app/models/mailing_list.rb
require "csv"

=begin
	MailingList:
		Contains a list of emails
	
	Database Variables:
		name:
			The name of the email
		description:
			A short description of the mailing list
		emails:
			All the emails associated with the Mailing List

	Relations
		emails(has and belongs to many):
			A mailing list has many emails
	TODO:

=end

class MailingList < ActiveRecord::Base
  attr_accessible :name, :description, :email_ids, :active, :emails, :dfile
  has_and_belongs_to_many :emails
    
  validates :name, :description, presence: true 

  def default_values
    self.active = false
  end

#Method: import
#		Imports a CVS or Excel to the mailing list 

	
  def import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)

    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      email = self.emails.find_by_emailAddress(row["emailAddress"]) || Email.new
      if(row["emailAddress"].to_s.include?("@"))
        email.attributes = row.to_hash.slice(*(Email.accessible_attributes))
        email.default_values
        email.save!
      end
      unless emails.include?(email)
        emails << email
      end
    end
  end


def self.import(self_id, attachment_id)
  list = MailingList.find(self_id)
  spreadsheet = MailingList.open(attachment_id)
  header = spreadsheet.row(1)

    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      email = list.emails.find_by_emailAddress(row["emailAddress"]) || Email.new
      if(row["emailAddress"].to_s.include?("@"))
        email.attributes = row.to_hash.slice(*(Email.accessible_attributes))
        email.default_values
        email.save!
      end
      unless list.emails.include?(email)
        list.emails << email
      end
    end
    list.save
end
	#Method: to_cvs
		#Exports the mailing list to a cvs format that can be edited and imported

  def to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << emails.column_names
	    emails.each do |email|
	      csv << email.attributes.values_at(*emails.column_names)
	   	end
	  end
  end


	#Method: open_spreadsheet

  def self.open(file_id)
    file = Attachment.find(file_id)
    Roo::Csv.new(file.path, nil, :ignore)
  end

  def open_spreadsheet(file)
    case File.extname(file.filename)
    when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.filename}"
    end
  end


  

  def remove_emails(emailids)
    emailids.each do |e|
          emails.delete(Email.find(e))
    end  
  end

  def add_emails(emailids)
    emailids.each do |eid|
      email =  Email.find(eid)
      unless emails.include?(email)
        emails << email
      end
    end
  end

end

app/controllers/mailing_lists_controller.rb
=begin
  MailingListController

  Views:
    index:
      List of all the mailing list. There is an potion to view edit delete
    show:
        List of emails
        Import xls and cvs
        Export cvs
        Remove check box
    create:
        

  
=end

class MailingListsController < ApplicationController
  # GET /mailing_lists
  # GET /mailing_lists.json
  def index
    @mailing_lists = MailingList.filter(:params => params)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mailing_lists }
      
    end
  end

  # GET /mailing_lists/1
  # GET /mailing_lists/1.json
  def show
    @mailing_list = MailingList.find(params[:id])
    @emails = @mailing_list.emails.filter(:params => params)
    @emails_all = Email.filter(:params => params)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mailing_list }
      format.csv { render :text => @mailing_list.to_csv }
    end
  end

  # GET /mailing_lists/new
  # GET /mailing_lists/new.json
  def new
    @mailing_list = MailingList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailing_list }
    end
  end

  # GET /mailing_lists/1/edit
  def edit
    @mailing_list = MailingList.find(params[:id])
  end

  # POST /mailing_lists
  # POST /mailing_lists.json
  def create
    @mailing_list = MailingList.new(params[:mailing_list])

    respond_to do |format|
      if @mailing_list.save
        format.html { redirect_to @mailing_list, notice: 'Mailing list was successfully created.' }
        format.json { render json: @mailing_list, status: :created, location: @mailing_list }
      else
        format.html { render action: "new" }
        format.json { render json: @mailing_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mailing_lists/1
  # PUT /mailing_lists/1.json
  def update
    @mailing_list = MailingList.find(params[:id])

    respond_to do |format|
      if @mailing_list.update_attributes(params[:mailing_list])
        format.html { redirect_to @mailing_list, notice: 'Mailing list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mailing_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailing_lists/1
  # DELETE /mailing_lists/1.json
  def destroy
    @mailing_list = MailingList.find(params[:id])
    @mailing_list.destroy

    respond_to do |format|
      format.html { redirect_to mailing_lists_url }
      format.json { head :no_content }
    end
  end

  def delete_many
    Email.destroyManyFromList(params[:list_id], params[:email_ids])
    redirect_to MailingList.find(params[:list_id]), notice: "Emails deleted."
  end

  def import
    mailing_list = MailingList.find(params[:list_id])
    file = params[:file]
    attachment = Attachment.create!(:data => file.read, :filename => file.original_filename, :path => file.path)
    MailingList.import(mailing_list.id, attachment.id)
    redirect_to mailing_list, notice: "Emails imported."
  end

  def remove_many
    mailing_list = MailingList.find(params[:list_id])
    mailing_list.remove_emails(params[:email_ids])
    redirect_to mailing_list, notice: "Emails Removed"
  end

  def add
    @mailing_list = MailingList.find(params[:id])
    @emails = Email.filter(:params => params)

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def add_emails
    mailing_list = MailingList.find(params[:list_id])
    mailing_list.add_emails(params[:email_ids])
    redirect_to mailing_list, notice: "Emails Added"
  end

end

app/helpers/mailing_lists_helper.rb
module MailingListsHelper
end

app/views/mailing_lists/_form.html.erb
<%= form_for(@mailing_list) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="action">
    <%= f.button :submit, label: "Add Mailing List" %>
  </div>
<% end %>

app/views/mailing_lists/add.html.erb
<h5> Add Emails </h5>
<br>

<%= will_filter_tag(@emails) %>
<%= form_tag add_emails_mailing_lists_path do %>
  <%= hidden_field_tag :list_id, @mailing_list.id %>
  <%= will_filter_table_tag(@emails, :columns => [
      :id, 
      { :key => :emailAddress,
          :value => lambda{|obj| 
            link_to(obj.emailAddress, obj) 
      }}, 
      :company,
      :title, 
      :first_name,
      :last_name,
      :address,
      :city,
      :state,
      :zip,
      { :key => :count,
          :value => lambda{|obj| 
            obj.count
      },:title => "Times Contacted"},  
      :visit_count,
      [:add, lambda{ |obj|
              actions = []  
              actions << check_box_tag("email_ids[]", obj.id)
              actions.join(' | ').html_safe
          },], 
       [:actions, lambda{ |obj|
                actions = []
                actions << link_to('Edit', edit_email_path(obj.id))   
                actions.join(' | ').html_safe
            },]
      ] )%>

    <%= submit_tag "Add Emails" %>
<% end %>

<%= link_to 'Edit', edit_mailing_list_path(@mailing_list) %> |
<%= link_to 'Back', @mailing_list%>

app/views/mailing_lists/edit.html.erb
<h1>Editing mailing_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @mailing_list %> |
<%= link_to 'Back', mailing_lists_path %>

app/views/mailing_lists/index.html.erb
<h1>Mailing Lists</h1>

<%= will_filter_tag(@mailing_lists) %>
<%= will_filter_table_tag(@mailing_lists, :columns => [
    :id, 
    {:key => :name,
      :value => lambda{|obj| 
          link_to(obj.name, obj) 
    },:title => "Name"},
    { :key => :count,
        :value => lambda{|obj| 
          obj.emails.size
    },:title => "Count"},  
    { :key => "Destroy",
        :value => lambda{|obj| 
          button_to('Destroy', obj, method: :delete, :class => :destroy, data: { confirm: 'Are you sure?' })
    },:title => "Destroy"},
     [:actions, lambda{ |obj|
              actions = []
              actions << link_to('Edit', :action => :edit, :id => obj.id)   
              actions.join(' | ').html_safe
          }, 'padding:3px;width:150px;padding-left:10px;']
    ] )%>

<br />

<%= link_to 'New Mailing list', new_mailing_list_path %>

app/views/mailing_lists/new.html.erb
<h1>Add Mailing List</h1>

<%= render 'form' %>

<%= link_to 'Back', mailing_lists_path %>

app/views/mailing_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h5><%= @mailing_list.name %></h5>
</p>

<p>
  Download:
  <%= link_to "CSV", mailing_list_path(format: "csv") %>
</p>

<h5> Emails </h5>
<br>
<%= will_filter_tag(@emails) %>
<%= form_tag remove_many_mailing_lists_path do %>
  <%= hidden_field_tag :list_id, @mailing_list.id %>
  <%= will_filter_table_tag(@emails, :columns => [
      :id, 
      :name,
      { :key => :emailAddress,
          :value => lambda{|obj| 
            link_to(obj.emailAddress, obj) 
      }},
      :company,
      :gender,
      :title, 
      :first_name,
      :last_name,
      :address,
      :city,
      :state,
      :zip,
      { :key => :count,
          :value => lambda{|obj| 
            obj.count
      },:title => "Times Contacted"}, 
      :visit_count, 
      [:remove, lambda{ |obj|
              actions = []  
              actions << check_box_tag("email_ids[]", obj.id)
              actions.join(' | ').html_safe
          },], 
       [:actions, lambda{ |obj|
                actions = []
                actions << link_to('Edit', edit_email_path(obj.id))
                actions.join(' | ').html_safe
            }, ]
      ] )%>

    <%= submit_tag "Remove Emails" %>
<% end %>


<h5>Import (.xls, .xlsx, and .cvs)</h5>
  
<%= form_tag import_mailing_lists_path(:list_id => @mailing_list.id), multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<p> <%= link_to 'Add Emails', add_mailing_lists_path(:id => @mailing_list.id) %></p>
 
<%= link_to 'Edit', edit_mailing_list_path(@mailing_list) %> |
<%= link_to 'Back', mailing_lists_path %>