config/routes.rb
MassMailer::Application.routes.draw do
  get "redirect/direct"

mount WillFilter::Engine => "/will_filter"
  mount Mercury::Engine => '/'

  resources :server_lists do
    collection do 
      post :remove_many
      post :add_servers
    end
  end

  resources :redirect, :only => :direct

  resources :list_mails do
    member do
      get :deliver
    end
  end

  resources :servers

  resources :mailing_lists do
    collection do 
      post :import
      post :remove_many
      post :add_emails
      get :add
    end
  end

  resources :email_submissions do
    member do
      get :deliver
    end
  end

  get "home_page/SendMail"

  get "scaffold/SendMail"

  resources :email_messages do
    member { post :update_html }
    member { get :view }
  end

  devise_for :users

  resources :emails 

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  match "/delayed_job" => DelayedJobWeb, :anchor => false
  match '/messagehtml' => 'email_messages#editor'
  match '/mailing_lists/:id/add' => 'mailing_lists#add'
  match '/view' => 'email_messages#view'
  root :to => 'list_mails#index'
end

app/models/server_list.rb
=begin
	ServerList:
		Contains a list of servers

	TODO:
		Work on this after list submission is completed
=end

class ServerList < ActiveRecord::Base
  attr_accessible :name, :server_ids, :servers
  has_and_belongs_to_many :servers

  validates :name, presence: true

  def add_server(server_id)
  	unless server_ids.include?(server_id)
  		server_ids << server_id
  	else
  		false
  	end
  end

  def get_active_servers
	servers_return = Array.new

	servers.each do |s|
		if s.is_active?
			servers_return << s
		end
	end

	servers_return
  end


 def remove_servers(serverids)
    serverids.each do |e|
          servers.delete(Server.find(e))
    end  
  end

  def add_servers(serverids)
    serverids.each do |sid|
      server =  Server.find(sid)
      unless servers.include?(server)
        servers << server
      end
    end
  end

end

app/controllers/server_lists_controller.rb
class ServerListsController < ApplicationController

	def show
   	 @server_list = ServerList.find(params[:id])
     @servers = @server_list.servers.filter(:params => params)
     @server_all = Server.filter(:params => params)
   	 respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server_list }
    	end
	end

    def new
    	@server_list = ServerList.new

    	respond_to do |format|
      		format.html # new.html.erb
    	end
  	end

  	def index
    	@server_lists = ServerList.filter(:params => params)

    	respond_to do |format|
      		format.html # index.html.erb
     		format.json { render json: @server_list }
    	end
  	end

  	def create
  		@server_list = ServerList.new(params[:server_list])
  		
	   	 respond_to do |format|
	      if @server_list.save
	        format.html { redirect_to @server_list, notice: 'Server List was successfully created.' }
	        format.json { render json: @server_list, status: :created, location: @server_list }
	      else
	        format.html { render action: "new" }
	        format.json { render json: @server_list.errors, status: :unprocessable_entity }
	      end
	  end
  	end	

  	def update
    @server_list = ServerList.find(params[:id])

    respond_to do |format|
      if @server_list.update_attributes(params[:server_list])
        format.html { redirect_to @server_list, notice: 'Owner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @server_list = ServerList.find(params[:id])
    @server_list.destroy

    respond_to do |format|
      format.html { redirect_to server_lists_url }
      format.json { head :no_content }
    end
  end

  def edit
    @server_list = ServerList.find(params[:id])
  end

  def remove_many
      server_list = ServerList.find(params[:server_list_id])
      server_list.remove_servers(params[:server_ids])
      redirect_to server_list, notice: "Servers Removed"
  end

  def add_servers
    server_list = ServerList.find(params[:server_list_id])
    server_list.add_servers(params[:server_ids])
    redirect_to server_list, notice: "Servers Added"
  end

end

app/helpers/server_lists_helper.rb
module ServerListsHelper
end

app/views/server_lists/_form.html.erb
<%= simple_form_for(@server_list) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/server_lists/edit.html.erb
<h5>Edit Server List</h5>

<%= render 'form' %>

<%= link_to 'Show', @server_list %> |
<%= link_to 'Back', server_lists_path %>

app/views/server_lists/index.html.erb
<h5>Sever List</h5>

<%= will_filter_tag(@server_lists) %>
<%= will_filter_table_tag(@server_lists, :columns => [
    :id, 
    {:key => :name,
      :value => lambda{|obj| 
          link_to(obj.name, obj) 
    },:title => "Name"},
    { :key => :count,
        :value => lambda{|obj| 
          obj.server_ids.size
    },:title => "Count"},  
    { :key => "Destroy",
        :value => lambda{|obj| 
          button_to('Destroy', obj, method: :delete, :class => :destroy, data: { confirm: 'Are you sure?' })
    },:title => "Destroy"},
     [:actions, lambda{ |obj|
              actions = []
              actions << link_to('Edit', :action => :edit, :id => obj.id)   
              actions.join(' | ').html_safe
          }, 'padding:3px;width:150px;padding-left:10px;']
    ] )%>

<br />

<%= link_to 'New Server List', new_server_list_path %>

app/views/server_lists/new.html.erb
<h5>New Server List</h5>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Back', server_lists_path %>

app/views/server_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h5>Server List : <%= @server_list.name %></h5>

<br>
<h5>Remove Server</h5>

<%= will_filter_tag(@servers) %>
<%= form_tag remove_many_server_lists_path do %>
	<%= hidden_field_tag :server_list_id, @server_list.id %>
<%= will_filter_table_tag(@servers, :columns => [
    :id, 
    { :key => :user_name,
        :value => lambda{|obj| 
          link_to(obj.user_name, obj) 
    }}, 
    :address, 
    :port, 
    :host, 
    :authentication,
    { :key => "Active",
        :value => lambda{|obj| 
          obj.isactive?
    }},  
    :count_day, 
    :max_emails,
    [:remove, lambda{ |obj|
              actions = []  
              actions << check_box_tag("server_ids[]", obj.id)
              actions.join(' | ').html_safe
          },], 
     [:actions, lambda{ |obj|
              actions = []
              actions << link_to('Edit', edit_server_path(obj.id))   
              actions.join(' | ').html_safe
          }, 'padding:3px;width:150px;padding-left:10px;']
    ] )%>


<%= submit_tag "Remove Servers" %>
<% end %>

<p></p>
<p></p>
<p></p>

<br>
<h5>Add Servers</h5>

	<%= will_filter_tag(@server_all) %>
	<%= form_tag add_servers_server_lists_path do %>
  	<%= hidden_field_tag :server_list_id, @server_list.id %>
	<%= will_filter_table_tag(@server_all, :columns => [
	    :id, 
	    { :key => :user_name,
	        :value => lambda{|obj| 
	          link_to(obj.user_name, obj) 
	    }}, 
	    :address, 
	    :port, 
	    :host, 
	    :authentication,
	    { :key => "Active",
	        :value => lambda{|obj| 
	          obj.isactive?
	    }},  
	    :count_day, 
	    :max_emails,
	    [:remove, lambda{ |obj|
	              actions = []  
	              actions << check_box_tag("server_ids[]", obj.id)
	              actions.join(' | ').html_safe
	          },], 
	     [:actions, lambda{ |obj|
	              actions = []
	              actions << link_to('Edit', edit_server_path(obj.id))  
	              actions.join(' | ').html_safe
	          }, 'padding:3px;width:150px;padding-left:10px;']
	    ] )%>

	<%= submit_tag "Add Servers" %>
<% end %>




<%= link_to 'Edit', edit_server_list_path(@server_list) %> |
<%= link_to 'Back', server_lists_path %>