config/routes.rb
MassMailer::Application.routes.draw do
  get "redirect/direct"

mount WillFilter::Engine => "/will_filter"
  mount Mercury::Engine => '/'

  resources :server_lists do
    collection do 
      post :remove_many
      post :add_servers
    end
  end

  resources :redirect, :only => :direct

  resources :list_mails do
    member do
      get :deliver
    end
  end

  resources :servers

  resources :mailing_lists do
    collection do 
      post :import
      post :remove_many
      post :add_emails
      get :add
    end
  end

  resources :email_submissions do
    member do
      get :deliver
    end
  end

  get "home_page/SendMail"

  get "scaffold/SendMail"

  resources :email_messages do
    member { post :update_html }
    member { get :view }
  end

  devise_for :users

  resources :emails 

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  match "/delayed_job" => DelayedJobWeb, :anchor => false
  match '/messagehtml' => 'email_messages#editor'
  match '/mailing_lists/:id/add' => 'mailing_lists#add'
  match '/view' => 'email_messages#view'
  root :to => 'list_mails#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Mass Mailer" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Mass Mailer", list_mails_path %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Email Submission", email_submissions_path %></li>   
      <li class="divider"></li>
      <li><%= link_to "Emails", emails_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Mailing Lists", mailing_lists_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Servers", servers_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Server Lists", server_lists_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Email Messages",  email_messages_path %></li>

      <% if user_signed_in? %>
      <li class="divider"></li>
      <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li class="divider"></li>
  	  <li> <%= link_to "Sign up", new_user_registration_path %> </li>
  	  <li class="divider"></li>
      <li> <%= link_to "Login", new_user_session_path %> </li>
	  <% end %>

    </ul>
  </div>
</nav>

  <body>
  	
    <div data-alert class="alert-box secondary">
      <br>
     <p>  <b>WARNING: </b>This is demo. Any data entered is visible to public. Do not post any private information.  </p>
    </div>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
  <hr>
  <p>Edwin Velasquez &copy; 2013  </p>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling._
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: 'POST', // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>