config/routes.rb
MassMailer::Application.routes.draw do
  get "redirect/direct"

mount WillFilter::Engine => "/will_filter"
  mount Mercury::Engine => '/'

  resources :server_lists do
    collection do 
      post :remove_many
      post :add_servers
    end
  end

  resources :redirect, :only => :direct

  resources :list_mails do
    member do
      get :deliver
    end
  end

  resources :servers

  resources :mailing_lists do
    collection do 
      post :import
      post :remove_many
      post :add_emails
      get :add
    end
  end

  resources :email_submissions do
    member do
      get :deliver
    end
  end

  get "home_page/SendMail"

  get "scaffold/SendMail"

  resources :email_messages do
    member { post :update_html }
    member { get :view }
  end

  devise_for :users

  resources :emails 

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  match "/delayed_job" => DelayedJobWeb, :anchor => false
  match '/messagehtml' => 'email_messages#editor'
  match '/mailing_lists/:id/add' => 'mailing_lists#add'
  match '/view' => 'email_messages#view'
  root :to => 'list_mails#index'
end

app/models/list_mail.rb
=begin

ListMail:
	ListMail sends a message to a list of email address from a list of servers. 

Database variables:
	:email_submissions (readable)
		Email that is ready to be sent. It contains emails, servers,
		and message to be sent. 
	:completed (r)
		Returns true if all the message were sent

	TODO:
		Add any variable that are not in the schema
		Delete all the variables that are not in use.
=end

class ListMail < ActiveRecord::Base
   attr_accessible :completed,:email_submission_ids, :message_id , :mailing_list_id, :server_id, :name, :priority, 
   	:server_list_id, :email_submissions, :count, :total_visit_count
   has_many :email_submissions
   validates :priority, numericality: {:greater_than_or_equal_to => 0}

   def init
   	self.completed = false
   	self.priority = 5
   	if ((self.name == nil) || (self.name == ""))
   		self.name = "Test Mass Mail #{self.id}"
   	end
   end

=begin
	Method: addSubmission
		Created a Mass Mail that can be sent at any point 
=end
	def addSubmissions(email_id, server_list_id, message_id, priority = 5)
		MailingList.find(email_id).emails.each do |e|
			submission = EmailSubmission.new
			submission.email_id = e.id
			submission.email_message_id = message_id
			submission.priority = priority
			submission.list_mail_id = self.id
			#params = [:email_id => e.id,  :email_message_id => message_id, :priority => priority, :list_mail_id => self.id]
			#submission.attributes = params
			submission.save
			email_submissions <<  submission
		end
	end 



	def select_random_server(slist)	
		offset = rand(slist.servers.count)
		
		if offset > 0
			slist.servers.first(:offset => offset)
		else
			false
		end
	end

=begin
	Method: deliver
		Deliver all email submissions
=end
	def deliver
	   	email_submissions.each do |e|
	   		if e.isdelivered == false
	   			EmailSubmission.delay(:queue => self.name, :priority => self.priority).deliver(e.id)
	   		end
	   	end
	end

	def amount_delivered
		count = 0
		email_submissions.each do |e|
			if e.isdelivered
				count = count + 1
			end
		end
		count
	end

	def total_submissions
		email_submissions.count
	end

	def completed?
		return_value = false
		if MailingList.find(mailing_list_id).emails.length == count
			return_value = true
		end
		return_value
	end

end

app/controllers/list_mails_controller.rb
=begin
	ListMail - Sends Mail to a list of people 

	
=end


class ListMailsController < ApplicationController
  before_filter :authenticate_user!, :only => [:deliver]

  def index
    @list_mails = ListMail.filter(:params => params)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @list_mails }  
    end
  end	

  def show
    @list_mail = ListMail.find(params[:id])
    @email_submissions = @list_mail.email_submissions.filter(:params => params)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list_mail }
    end
  end

  def new
    @list_mail = ListMail.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list_mail }
    end
  end

  def create
     @list_mail = ListMail.new(params[:list_mail])
     @list_mail.addSubmissions(@list_mail.mailing_list_id, @list_mail.server_list_id, @list_mail.message_id)
     @list_mail.init
    respond_to do |format|
	    if @list_mail.save

	      format.html {redirect_to @list_mail, notice: "List Mail was successfully created"}
	      format.json { render json: @list_mail }
	    else
	        format.html { render action: "new" }
	        format.json { render json: @list_mail.errors, status: :unprocessable_entity }
	    end
    end
  end

    def destroy
    list_mail = ListMail.find(params[:id])
    list_mail.destroy

    respond_to do |format|
      format.html { redirect_to list_mails_url }
      format.json { head :no_content }
    end
  end

  def deliver
    @list_mail = ListMail.find(params[:id])
    @list_mail.deliver

    respond_to do |format|
      format.html { redirect_to list_mails_path, notce: "Emails are being sent" }
      format.json { head :no_content }
    end
  end
	
end

app/helpers/list_mails_helper.rb
module ListMailsHelper
end

app/views/list_mails/_form.html.erb
<%= simple_form_for @list_mail do |f| %>
<%= f.input :name, label: "Name: " %>
<%= f.label "Server List:" %>
<%= f.collection_select(:server_list_id, ServerList.all, :id, :name )%>
<%= f.label "Mailing List:" %>
<%= f.collection_select(:mailing_list_id, MailingList.all, :id, :name) %>
<%= f.label "Messsage:" %>
<%= f.collection_select(:message_id, EmailMessage.all, :id, :label) %>
<%= f.input :priority, label: "Priority (0 = Highest Priority):" %>
<%= f.button :submit, "Send Emails" %>
<% end %>

app/views/list_mails/index.html.erb
<h5>Mass Mail</h5>

<%= will_filter_tag(@list_mails) %>
<%= will_filter_table_tag(@list_mails, :columns => [
    :id, 
    {:key => :name,
      :value => lambda{|obj| 
          link_to(obj.name, obj) 
    },:title => "Name"},
    {:key => :mailing_list_id,
      :value => lambda{|obj| 
           link_to(MailingList.find(obj.mailing_list_id).name, MailingList.find(obj.mailing_list_id))
    },:title => "Mailing List"},
    {:key => :email_message_id,
      :value => lambda{|obj| 
           link_to(EmailMessage.find(obj.message_id).label, EmailMessage.find(obj.message_id))
    },:title => "Message"},
    {:key => :mailing_list_id,
      :value => lambda{|obj| 
           link_to(ServerList.find(obj.server_list_id).name, ServerList.find(obj.server_list_id)) 
    },:title => "Server ist"},
    {:key => "Amount Delivered",
      :value => lambda{|obj| 
          "#{obj.amount_delivered} / #{obj.total_submissions}"
    },:title => "Amount Delivered"},
    :total_visit_count,
    { :key => :priority,
        :value => lambda{|obj| 
          obj.priority
    },:title => "Priority"},  
    { :key => :send,
        :value => lambda{|obj| 
          link_to("Send", deliver_list_mail_path(obj))
    },:title => "Send"},
    { :key => "Destroy",
        :value => lambda{|obj| 
          button_to('Destroy', obj, method: :delete, :class => :destroy, data: { confirm: 'Are you sure?' })
    },:title => "Destroy"},
     [:actions, lambda{ |obj|
              actions = []
              actions << link_to('Edit', :action => :edit, :id => obj.id)   
              actions.join(' | ').html_safe
          }, 'padding:3px;width:150px;padding-left:10px;']
    ] )%>

<br />

<%= link_to 'New Mass Mail', new_list_mail_path %>

app/views/list_mails/new.html.erb
<h1>Create a Mass Mail</h1>

<%= render 'form' %>

<%= link_to 'Back', list_mails_path %>

app/views/list_mails/show.html.erb
<p id="notice"><%= notice %></p>

<h4>Email Submissions</h4>

<%= will_filter_tag(@email_submissions) %>
<%= will_filter_table_tag(@email_submissions, :columns => [
    :id, 
    { :key => lambda{|obj|  
          Email.find(obj.email_id).emailAddress},          
        :value => lambda{|obj| 
          link_to(Email.find(obj.email_id).emailAddress,Email.find(obj.email_id))
    }, :title => "Email Address" }, 
    { :key => lambda{|obj|  
          EmailMessage.find(obj.email_message_id).label},
        :value => lambda{|obj| 
          link_to(EmailMessage.find(obj.email_message_id).label, EmailMessage.find(obj.email_message_id))
    },:title => "Message Name"},  
    { :key => "Delivered",
        :value => lambda{|obj| 
          obj.isdelivered?
    },:title => "Delivered"},  
    :priority, 
    :visit_count,
    { :key => "Destroy",
        :value => lambda{|obj| 
          button_to('Destroy', obj, method: :delete, :class => :destroy, data: { confirm: 'Are you sure?' })
    },:title => "Destroy"},
     [:actions, lambda{ |obj|
              actions = []
              actions << link_to("Send", deliver_email_submission_path(obj))
              actions << link_to('Edit', edit_email_submission_path(obj))  
              actions.join(' | ').html_safe
          }, 'padding:3px;width:150px;padding-left:10px;']
    ] )%>


<br />

<%= link_to 'Edit', edit_list_mail_path(@list_mail) %> |
<%= link_to 'Back', list_mails_path %>